AWSTemplateFormatVersion: '2010-09-09'
Description: "Create a ec2 server with sg using CF"

# Parameters:
#   KeyName:
#     Description: Name of an existing key-pair 
#     Type: AWS::EC2::KeyPair

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyEC2Instane: 
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0cfde0ea8edd312d4
      # KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags: 
        - Key: Name
          Value: MyEC2Instane-demo