AWSTemplateFormatVersion: '2010-09-09'
Description: "Create a ec2 server with sg using CF"
Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: Enter EC2 Instance Type
    AllowedValues: 
      - t2.micro
      - t2.small
      - t2.medium
      - t3.micro 
    ConstraintDescription: must be a valid EC2 instance type fro the list above
Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyEC2Instane: 
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-00af95fa354fdb788
      # KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags: 
        - Key: Name
          Value: MyEC2Instane-demo

Outputs: 
  InstanceId: 
    Description: The instance id of the ec2
    Value : !Ref MyEC2Instane